[package]
name = "anglosaxon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs ="0.8"
anyhow = "1.0"
clap = { version = "3", features = ["unstable-grouped"] }
